/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ecliptest_MyDest */

#ifndef _Included_com_example_ecliptest_MyDest
#define _Included_com_example_ecliptest_MyDest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ecliptest_MyDest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ecliptest_MyDest_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ecliptest_MyDest
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_ecliptest_MyDest_init
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_ecliptest_MyDest
 * Method:    decode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ecliptest_MyDest_decode
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ecliptest_MyDest
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ecliptest_MyDest_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
