/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ecliptest_MyDest */

#ifndef _Included_com_example_ecliptest_MyDest
#define _Included_com_example_ecliptest_MyDest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ecliptest_MyDest
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ecliptest_MyDest_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
